version: '2'
services:
    zookeeper:
        image: 'wurstmeister/zookeeper:latest'
        hostname: zookeeper
        ports:
            - '2181:2181'
    kafka:
        image: 'wurstmeister/kafka:0.10.2.1'
        ports:
            - '9092:9092'
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
            KAFKA_CREATE_TOPICS: 'mytopic:2:1'
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        depends_on:
            - zookeeper
    nimbus:
        image: sunside/storm-nimbus
        container_name: storm-nimbus
        hostname: storm-nimbus
        ports:
            - '49773:49772'
            - '49772:49773'
            - '49627:49627'
        links:
            - zookeeper
        environment:
            - LOCAL_HOSTNAME=storm-nimbus
            - ZOOKEEPER_ADDRESS=zookeeper
            - ZOOKEEPER_PORT=2181
            - NIMBUS_ADDRESS=storm-nimbus
            - NIMBUS_THRIFT_PORT=49627
            - DRPC_PORT=49772
            - DRPCI_PORT=49773
    supervisor:
        image: sunside/storm-supervisor
        container_name: storm-supervisor
        hostname: storm-supervisor
        ports:
            - '8000:8000'
        links:
            - zookeeper
            - nimbus
        environment:
            - LOCAL_HOSTNAME=storm-supervisor
            - NIMBUS_ADDRESS=storm-nimbus
            - NIMBUS_THRIFT_PORT=49627
            - DRPC_PORT=49772
            - DRPCI_PORT=49773
            - ZOOKEEPER_ADDRESS=zookeeper
            - ZOOKEEPER_PORT=2181
    ui:
        image: sunside/storm-ui
        container_name: storm-ui
        hostname: storm-ui
        ports:
            - '49080:8080'
        links:
            - zookeeper
            - nimbus
        environment:
            - LOCAL_HOSTNAME=storm-ui
            - NIMBUS_ADDRESS=storm-nimbus
            - NIMBUS_THRIFT_PORT=49627
            - DRPC_PORT=49772
            - DPRCI_PORT=49773
            - ZOOKEEPER_ADDRESS=zookeeper
            - ZOOKEEPER_PORT=2181
    flume:
        image: pschatzmann/flume
        container_name: flume
        volumes:
            - /srv/flume/plugins.d:/flume/plugins.d
            - /srv/flume/conf:/flume/conf
        restart: always
        environment:
            - LOGGER=INFO,console
